# Auto-generated stub for flowfile_frame.cloud_storage.secret_manager — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from flowfile_core.schemas.cloud_storage_schemas import FullCloudStorageConnection, FullCloudStorageConnectionInterface

def get_current_user_id() -> int | None: ...
def create_cloud_storage_connection(connection: FullCloudStorageConnection) -> None: ...
def create_cloud_storage_connection_if_not_exists(connection: FullCloudStorageConnection) -> None: ...
def get_all_available_cloud_storage_connections() -> list[FullCloudStorageConnectionInterface]: ...
def del_cloud_storage_connection(connection_name: str) -> None: ...
