"""Guard that the notebook editor's committed ``ff.`` completions match ``flowfile.__all__``.

The cell editor completes ``ff.`` names from a JSON file generated by
``tools/generate_fl_completions.py``. A new public name that nobody regenerated for would silently never be
offered, so regeneration must offer the same names as the committed file (byte equality is the make target's job).
"""

import json

from tools import generate_fl_completions as gen


def test_committed_file_exists():
    assert gen.OUTPUT_PATH.is_file(), f"{gen.OUTPUT_PATH} is missing — run 'make fl_completions'"


def _names(payload: str) -> dict[str, list[tuple[str, str | None]]]:
    """The (name, kind) pairs per section: what the editor offers, independent of the signature spelling."""
    data = json.loads(payload)
    return {section: [(e["name"], e.get("kind")) for e in entries] for section, entries in data.items()}


def test_regeneration_offers_the_committed_names():
    """Signatures and docstrings differ between Python and Polars versions, so CI compares the names offered.

    ``make check_fl_completions`` remains the byte-exact gate, run locally with the toolchain that generated the file.
    """
    committed = gen.OUTPUT_PATH.read_text(encoding="utf-8")
    assert _names(gen.render()) == _names(committed), (
        "ff completions are stale — run 'make fl_completions' and commit the result"
    )


def test_shape_is_sorted_and_covers_the_api():
    data = json.loads(gen.OUTPUT_PATH.read_text(encoding="utf-8"))
    assert set(data) == {"ff"}
    for section, entries in data.items():
        names = [e["name"] for e in entries]
        assert names == sorted(names) and len(names) == len(set(names)), section
        assert all(not n.startswith("_") for n in names), section
    import flowfile

    ff = {e["name"]: e for e in data["ff"]}
    assert set(ff) == set(flowfile.__all__)
    assert {e["kind"] for e in data["ff"]} <= {"function", "class", "module", "constant"}
    assert ff["read_csv"]["kind"] == "function" and ff["read_csv"]["signature"].startswith("(source")
    assert ff["FlowFrame"]["kind"] == "class"
