# Auto-generated stub for flowfile_frame.database.connection_manager — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from typing import Literal
from pydantic import SecretStr
from flowfile_core.schemas.input_schema import FullDatabaseConnection, FullDatabaseConnectionInterface

def get_current_user_id() -> int: ...
def create_database_connection(connection_name: str, *, database_type: Literal['postgresql', 'mysql', 'sqlite', 'mssql', 'oracle']='postgresql', host: str | None=None, port: int | None=None, database: str | None=None, username: str | None=None, password: str | SecretStr | None=None, ssl_enabled: bool=False, url: str | None=None) -> FullDatabaseConnection: ...
def create_database_connection_if_not_exists(connection_name: str, *, database_type: Literal['postgresql', 'mysql', 'sqlite', 'mssql', 'oracle']='postgresql', host: str | None=None, port: int | None=None, database: str | None=None, username: str | None=None, password: str | SecretStr | None=None, ssl_enabled: bool=False, url: str | None=None) -> FullDatabaseConnection: ...
def get_database_connection_by_name(connection_name: str) -> FullDatabaseConnection | None: ...
def get_all_available_database_connections() -> list[FullDatabaseConnectionInterface]: ...
def del_database_connection(connection_name: str) -> bool: ...
