<template>
  <div class="artifact-detail">
    <button class="back-btn" @click="$emit('close')">
      <i class="fa-solid fa-arrow-left"></i> Back
    </button>
    <!-- Header -->
    <div class="detail-header">
      <div class="header-main">
        <div class="header-title">
          <i class="fa-solid fa-cube header-icon"></i>
          <h2>{{ artifact.name }}</h2>
          <span v-if="isUnavailable" class="status-badge unavailable">unavailable</span>
          <span v-else class="status-badge" :class="artifact.status">{{ artifact.status }}</span>
          <SharedBadge :access="artifact.access" />
        </div>
        <p v-if="artifact.description" class="description">{{ artifact.description }}</p>
      </div>
      <div class="header-actions">
        <button
          v-if="canShare(artifact)"
          class="btn btn-secondary btn-sm"
          title="Share model"
          @click="showShareDialog = true"
        >
          <i class="fa-solid fa-share-nodes"></i>
          Share
        </button>
        <button
          v-if="canManage(artifact) && totalVersions > 1"
          class="btn btn-secondary btn-sm"
          title="Delete older versions"
          @click="showPruneDialog = true"
        >
          <i class="fa-solid fa-broom"></i>
          Prune versions
        </button>
        <button
          v-if="canManage(artifact)"
          class="btn btn-danger btn-sm"
          title="Delete model"
          @click="emit('deleteArtifact', artifact)"
        >
          <i class="fa-solid fa-trash"></i>
          Delete
        </button>
      </div>
    </div>

    <ShareDialog
      v-if="artifact.id != null"
      v-model="showShareDialog"
      resource-type="global_artifact"
      :resource-id="artifact.id"
      :resource-name="artifact.name"
      :can-manage-grants="canManageGrants(artifact)"
    />

    <ArtifactPruneDialog
      v-model="showPruneDialog"
      :artifact-name="artifact.name"
      :total-versions="totalVersions"
      :versions="versions"
      @pruned="emit('versionsChanged')"
    />

    <!-- Data missing banner -->
    <div v-if="isUnavailable" class="missing-banner">
      <i class="fa-solid fa-triangle-exclamation"></i>
      <div>
        <strong>Model data not found</strong>
        <p>
          The data file for this model no longer exists on disk. It cannot be loaded in flows until
          it is regenerated by rerunning the flow that produced it.
        </p>
      </div>
    </div>

    <!-- Metadata Grid -->
    <div class="meta-grid">
      <div class="meta-card">
        <span class="meta-label">Type</span>
        <span class="meta-value mono">{{ formatType(artifact) }}</span>
      </div>
      <div class="meta-card">
        <span class="meta-label">Format</span>
        <span class="meta-value">{{ artifact.serialization_format ?? "unknown" }}</span>
      </div>
      <div class="meta-card">
        <span class="meta-label">Size</span>
        <span class="meta-value">{{ formatSize(artifact.size_bytes) }}</span>
      </div>
      <div class="meta-card">
        <span class="meta-label">Latest Version</span>
        <span class="meta-value">v{{ artifact.version }}</span>
      </div>
      <div class="meta-card">
        <span class="meta-label">Total Versions</span>
        <span class="meta-value">{{ totalVersions }}</span>
      </div>
      <div class="meta-card">
        <span class="meta-label">Created</span>
        <span class="meta-value">{{
          artifact.created_at ? formatDate(artifact.created_at) : "--"
        }}</span>
      </div>
    </div>

    <!-- Technical Details -->
    <div class="section">
      <h3>Details</h3>
      <div class="detail-list">
        <div v-if="artifact.python_type" class="detail-row">
          <span class="detail-label">Python Type</span>
          <span class="detail-value mono">{{ artifact.python_type }}</span>
        </div>
        <div v-if="artifact.python_module" class="detail-row">
          <span class="detail-label">Module</span>
          <span class="detail-value mono">{{ artifact.python_module }}</span>
        </div>
        <div v-if="artifact.sha256" class="detail-row">
          <span class="detail-label">SHA-256</span>
          <span class="detail-value mono sha">{{ artifact.sha256 }}</span>
        </div>
        <div v-if="sourceFlowName" class="detail-row">
          <span class="detail-label">Source Flow</span>
          <span
            class="detail-value flow-link"
            @click="emit('navigate-to-flow', artifact.source_registration_id!)"
            >{{ sourceFlowName }}</span
          >
        </div>
        <div v-else-if="artifact.source_registration_id" class="detail-row">
          <span class="detail-label">Source Flow</span>
          <span class="detail-value mono">ID {{ artifact.source_registration_id }}</span>
        </div>
        <div v-if="artifact.source_node_id" class="detail-row">
          <span class="detail-label">Source Node</span>
          <span class="detail-value">Node {{ artifact.source_node_id }}</span>
        </div>
      </div>
    </div>

    <!-- Tags -->
    <div v-if="artifact.tags && artifact.tags.length > 0" class="section">
      <h3>Tags</h3>
      <div class="tags-list">
        <span v-for="tag in artifact.tags" :key="tag" class="tag-badge">{{ tag }}</span>
      </div>
    </div>

    <!-- Versions Table -->
    <div v-if="totalVersions > 0" class="section">
      <h3>Versions</h3>
      <div class="versions-table">
        <div class="versions-header">
          <span class="col-version">Version</span>
          <span class="col-type">Type</span>
          <span class="col-size">Size</span>
          <span class="col-date">Created</span>
          <span class="col-actions">Actions</span>
        </div>
        <div v-if="loadingVersions" class="versions-loading">Loading versions…</div>
        <template v-else>
          <div
            v-for="v in versions"
            :key="v.id"
            class="versions-row"
            :class="{ current: isLatest(v.version, latestVersion) }"
          >
            <span class="col-version">
              v{{ v.version }}
              <span v-if="isLatest(v.version, latestVersion)" class="latest-tag">latest</span>
              <el-tooltip
                v-if="v.blob_exists === false"
                content="Model data file not found on disk"
                placement="top"
                :show-after="300"
              >
                <i class="fa-solid fa-triangle-exclamation missing-icon"></i>
              </el-tooltip>
            </span>
            <span class="col-type mono">{{ versionType(v) }}</span>
            <span class="col-size">{{ formatSize(v.size_bytes) }}</span>
            <span class="col-date">{{ v.created_at ? formatDate(v.created_at) : "--" }}</span>
            <span class="col-actions">
              <template v-if="canManage(artifact) && !isLatest(v.version, latestVersion)">
                <el-tooltip content="Restore as newest version" placement="top" :show-after="400">
                  <el-button size="small" text @click="emit('promoteVersion', v)">
                    <i class="fa-solid fa-rotate-left" />
                  </el-button>
                </el-tooltip>
                <el-tooltip content="Delete this version" placement="top" :show-after="400">
                  <el-button size="small" type="danger" text @click="emit('deleteVersion', v)">
                    <i class="fa-solid fa-trash" />
                  </el-button>
                </el-tooltip>
              </template>
            </span>
          </div>
        </template>
      </div>

      <div v-if="totalPages > 1" class="pagination-bar">
        <button class="page-btn" :disabled="page <= 1" @click="emit('setVersionsPage', 1)">
          <i class="fa-solid fa-angles-left" />
        </button>
        <button class="page-btn" :disabled="page <= 1" @click="emit('setVersionsPage', page - 1)">
          <i class="fa-solid fa-angle-left" />
        </button>
        <span class="page-info">Page {{ page }} of {{ totalPages }}</span>
        <button
          class="page-btn"
          :disabled="page >= totalPages"
          @click="emit('setVersionsPage', page + 1)"
        >
          <i class="fa-solid fa-angle-right" />
        </button>
        <button
          class="page-btn"
          :disabled="page >= totalPages"
          @click="emit('setVersionsPage', totalPages)"
        >
          <i class="fa-solid fa-angles-right" />
        </button>
      </div>
    </div>

    <!-- Usage Example -->
    <div class="section">
      <h3>Usage</h3>
      <div class="code-block">
        <code>obj = flowfile_ctx.get_global("{{ usageRef }}")</code>
      </div>
      <div v-if="totalVersions > 1" class="code-block" style="margin-top: 8px">
        <code>obj_v1 = flowfile_ctx.get_global("{{ usageRef }}", version=1)</code>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { useCatalogStore } from "../../stores/catalog-store";
import { findNamespacePath, type ArtifactVersionInfo, type GlobalArtifact } from "../../types";
import { formatDate, formatPythonType, formatSize, formatType } from "./catalog-formatters";
import {
  artifactRef,
  isLatest,
  latestVersionNumber,
  totalPages as computeTotalPages,
} from "./artifactVersions";
import ArtifactPruneDialog from "./ArtifactPruneDialog.vue";
import ShareDialog from "../../components/sharing/ShareDialog.vue";
import SharedBadge from "../../components/sharing/SharedBadge.vue";
import { useResourceSharing } from "../../composables/useResourceSharing";

const showShareDialog = ref(false);
const showPruneDialog = ref(false);
const { canShare, canManage, canManageGrants } = useResourceSharing();

const props = defineProps<{
  artifact: GlobalArtifact;
  versions: ArtifactVersionInfo[];
  totalVersions: number;
  page: number;
  loadingVersions?: boolean;
}>();

const emit = defineEmits([
  "close",
  "navigate-to-flow",
  "deleteArtifact",
  "deleteVersion",
  "promoteVersion",
  "setVersionsPage",
  "versionsChanged",
]);

const catalogStore = useCatalogStore();

const totalPages = computed(() => computeTotalPages(props.totalVersions));

// Latest is the highest version number, never row-id equality: a promote mints a
// new max version and leaves the panel's own row behind.
const latestVersion = computed(() => latestVersionNumber(props.artifact.version, props.versions));

const isUnavailable = computed(() => props.artifact.blob_exists === false);

// Same fallback the Type meta card uses, so one artifact never reads two ways.
const versionType = (v: ArtifactVersionInfo): string =>
  formatPythonType(v.python_type, props.artifact.serialization_format ?? "unknown");

const sourceFlowName = computed((): string | null => {
  const regId = props.artifact.source_registration_id;
  if (regId === null) return null;
  const flow = catalogStore.allFlows.find((f) => f.id === regId);
  return flow?.name ?? null;
});

// Qualified reference for the usage snippet so it resolves unambiguously when
// the same name exists in multiple schemas; bare name when unnamespaced.
const usageRef = computed((): string => {
  const id = props.artifact.namespace_id;
  const path = id === null || id === undefined ? [] : findNamespacePath(catalogStore.tree, id);
  return artifactRef(props.artifact.name, path);
});
</script>

<style scoped>
.artifact-detail {
  max-width: 1000px;
  margin: 0 auto;
}

.detail-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: var(--spacing-5);
}

.header-actions {
  display: flex;
  gap: var(--spacing-2);
}

.header-title {
  display: flex;
  align-items: center;
  gap: var(--spacing-2);
}

/* ========== Missing File Banner ========== */
.missing-banner {
  display: flex;
  align-items: flex-start;
  gap: var(--spacing-3);
  padding: var(--spacing-3) var(--spacing-4);
  margin-bottom: var(--spacing-4);
  background: color-mix(in srgb, var(--color-warning) 8%, transparent);
  border: 1px solid color-mix(in srgb, var(--color-warning) 30%, transparent);
  border-radius: var(--border-radius-md);
  color: var(--color-text-primary);
}

.missing-banner > i {
  color: var(--color-warning);
  font-size: var(--font-size-lg);
  margin-top: 2px;
  flex-shrink: 0;
}

.missing-banner strong {
  font-size: var(--font-size-sm);
  display: block;
  margin-bottom: var(--spacing-1);
}

.missing-banner p {
  margin: 0;
  font-size: var(--font-size-xs);
  color: var(--color-text-secondary);
  line-height: 1.5;
}

.missing-icon {
  font-size: 11px;
  color: var(--color-warning);
  margin-left: 4px;
}

.header-icon {
  color: var(--color-primary);
  font-size: var(--font-size-xl);
}

.header-title h2 {
  margin: 0;
  font-size: var(--font-size-xl);
  font-weight: var(--font-weight-semibold);
  color: var(--color-text-primary);
}

.description {
  margin: var(--spacing-2) 0 0;
  color: var(--color-text-secondary);
  font-size: var(--font-size-sm);
}

/* ========== Detail List ========== */
.detail-list {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-2);
}

.detail-row {
  display: flex;
  align-items: baseline;
  gap: var(--spacing-3);
  padding: var(--spacing-2) var(--spacing-3);
  background: var(--color-background-secondary);
  border-radius: var(--border-radius-md);
  border: 1px solid var(--color-border-light);
}

.detail-label {
  font-size: var(--font-size-xs);
  color: var(--color-text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  min-width: 100px;
  flex-shrink: 0;
}

.detail-value {
  font-size: var(--font-size-sm);
  color: var(--color-text-primary);
}

.detail-value.mono {
  font-family: var(--font-family-mono);
  font-size: var(--font-size-xs);
  word-break: break-all;
}

.detail-value.sha {
  font-size: 11px;
  color: var(--color-text-muted);
}

.detail-value.flow-link {
  color: var(--color-primary);
  cursor: pointer;
  font-weight: var(--font-weight-medium);
}

.detail-value.flow-link:hover {
  text-decoration: underline;
}

/* ========== Tags ========== */
.tags-list {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-1);
}

.tag-badge {
  font-size: var(--font-size-xs);
  padding: 2px 8px;
  border-radius: var(--border-radius-full);
  background: var(--color-background-secondary);
  border: 1px solid var(--color-border-light);
  color: var(--color-text-secondary);
}

/* ========== Versions Table ========== */
.versions-table {
  border: 1px solid var(--color-border-light);
  border-radius: var(--border-radius-md);
  overflow: hidden;
}

.versions-header {
  display: grid;
  grid-template-columns: 120px 1fr 80px 140px 96px;
  gap: var(--spacing-2);
  padding: var(--spacing-2) var(--spacing-3);
  background: var(--color-background-tertiary);
  font-size: var(--font-size-xs);
  color: var(--color-text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  font-weight: var(--font-weight-medium);
}

.versions-row {
  display: grid;
  grid-template-columns: 120px 1fr 80px 140px 96px;
  gap: var(--spacing-2);
  padding: var(--spacing-2) var(--spacing-3);
  font-size: var(--font-size-sm);
  border-top: 1px solid var(--color-border-light);
  transition: background var(--transition-fast);
}

.versions-row:hover {
  background: var(--color-background-hover);
}

.versions-loading {
  padding: var(--spacing-4);
  text-align: center;
  color: var(--color-text-muted);
  font-size: var(--font-size-sm);
  border-top: 1px solid var(--color-border-light);
}

.versions-row.current {
  background: var(--color-background-selected);
}

.latest-tag {
  display: inline-block;
  font-size: 10px;
  padding: 0 4px;
  border-radius: var(--border-radius-sm);
  background: var(--color-primary);
  color: var(--color-text-inverse);
  margin-left: 4px;
  line-height: 16px;
  vertical-align: middle;
}

/* ========== Code Block ========== */
.code-block {
  background: var(--color-background-secondary);
  border: 1px solid var(--color-border-light);
  border-radius: var(--border-radius-md);
  padding: var(--spacing-3);
}

.code-block code {
  font-family: var(--font-family-mono);
  font-size: var(--font-size-sm);
  color: var(--color-text-primary);
}
</style>
