"""Numeric defaults and limits for the catalog domain.

Centralised so call sites read intent rather than literals.
"""

DEFAULT_PREVIEW_LIMIT = 100
MAX_PREVIEW_LIMIT = 1000
MAX_VISUALIZATION_ROWS = 500_000
DEFAULT_VISUALIZATION_ROWS = 100_000
MAX_THUMBNAIL_BYTES = 500_000
DEFAULT_SQL_MAX_ROWS = 10_000
MIN_SCHEDULE_INTERVAL_SECONDS = 60
QUERY_VIRTUAL_TABLE_RECURSION_LIMIT = 5

# save_sql_query_as_flow node-layout positions
SAVED_FLOW_NODE_X = 100
SAVED_FLOW_NODE_Y_STEP = 150
SAVED_FLOW_SQL_NODE_X = 400
SAVED_FLOW_SQL_NODE_Y = 200
