# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import worker_service_pb2 as worker__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """Worker service for dataframe processing operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitQuery = channel.unary_unary(
                '/flowfile.worker.WorkerService/SubmitQuery',
                request_serializer=worker__service__pb2.SubmitQueryRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StoreSample = channel.unary_unary(
                '/flowfile.worker.WorkerService/StoreSample',
                request_serializer=worker__service__pb2.StoreSampleRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AddFuzzyJoin = channel.unary_unary(
                '/flowfile.worker.WorkerService/AddFuzzyJoin',
                request_serializer=worker__service__pb2.FuzzyJoinRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateTable = channel.unary_unary(
                '/flowfile.worker.WorkerService/CreateTable',
                request_serializer=worker__service__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StoreDatabaseReadResult = channel.unary_unary(
                '/flowfile.worker.WorkerService/StoreDatabaseReadResult',
                request_serializer=worker__service__pb2.DatabaseReadRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StoreDatabaseWriteResult = channel.unary_unary(
                '/flowfile.worker.WorkerService/StoreDatabaseWriteResult',
                request_serializer=worker__service__pb2.DatabaseWriteRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.WriteDataToCloud = channel.unary_unary(
                '/flowfile.worker.WorkerService/WriteDataToCloud',
                request_serializer=worker__service__pb2.CloudStorageWriteRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.WriteResults = channel.unary_unary(
                '/flowfile.worker.WorkerService/WriteResults',
                request_serializer=worker__service__pb2.WriteResultsRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/flowfile.worker.WorkerService/GetStatus',
                request_serializer=worker__service__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/flowfile.worker.WorkerService/StreamStatus',
                request_serializer=worker__service__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=worker__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.FetchResults = channel.unary_unary(
                '/flowfile.worker.WorkerService/FetchResults',
                request_serializer=worker__service__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=worker__service__pb2.FetchResultsResponse.FromString,
                _registered_method=True)
        self.GetMemoryUsage = channel.unary_unary(
                '/flowfile.worker.WorkerService/GetMemoryUsage',
                request_serializer=worker__service__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=worker__service__pb2.MemoryUsageResponse.FromString,
                _registered_method=True)
        self.GetAllTaskIds = channel.unary_unary(
                '/flowfile.worker.WorkerService/GetAllTaskIds',
                request_serializer=worker__service__pb2.Empty.SerializeToString,
                response_deserializer=worker__service__pb2.TaskIdsResponse.FromString,
                _registered_method=True)
        self.ClearTask = channel.unary_unary(
                '/flowfile.worker.WorkerService/ClearTask',
                request_serializer=worker__service__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=worker__service__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/flowfile.worker.WorkerService/CancelTask',
                request_serializer=worker__service__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=worker__service__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/flowfile.worker.WorkerService/Shutdown',
                request_serializer=worker__service__pb2.Empty.SerializeToString,
                response_deserializer=worker__service__pb2.MessageResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Worker service for dataframe processing operations
    """

    def SubmitQuery(self, request, context):
        """Submit a dataframe query for processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreSample(self, request, context):
        """Store a sample of a dataframe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFuzzyJoin(self, request, context):
        """Execute a fuzzy join operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        """Create a table from received data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreDatabaseReadResult(self, request, context):
        """Read from database and store result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreDatabaseWriteResult(self, request, context):
        """Write dataframe to database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteDataToCloud(self, request, context):
        """Write dataframe to cloud storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteResults(self, request, context):
        """Write dataframe to file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get task status (unary call)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Stream task status updates (server streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchResults(self, request, context):
        """Fetch completed task results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryUsage(self, request, context):
        """Get memory usage for a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTaskIds(self, request, context):
        """Get all task IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearTask(self, request, context):
        """Clear a task and its cached files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Cancel a running task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown the worker gracefully
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitQuery,
                    request_deserializer=worker__service__pb2.SubmitQueryRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'StoreSample': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreSample,
                    request_deserializer=worker__service__pb2.StoreSampleRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'AddFuzzyJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFuzzyJoin,
                    request_deserializer=worker__service__pb2.FuzzyJoinRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=worker__service__pb2.CreateTableRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'StoreDatabaseReadResult': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreDatabaseReadResult,
                    request_deserializer=worker__service__pb2.DatabaseReadRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'StoreDatabaseWriteResult': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreDatabaseWriteResult,
                    request_deserializer=worker__service__pb2.DatabaseWriteRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'WriteDataToCloud': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteDataToCloud,
                    request_deserializer=worker__service__pb2.CloudStorageWriteRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'WriteResults': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteResults,
                    request_deserializer=worker__service__pb2.WriteResultsRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=worker__service__pb2.TaskIdRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=worker__service__pb2.TaskIdRequest.FromString,
                    response_serializer=worker__service__pb2.StatusResponse.SerializeToString,
            ),
            'FetchResults': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchResults,
                    request_deserializer=worker__service__pb2.TaskIdRequest.FromString,
                    response_serializer=worker__service__pb2.FetchResultsResponse.SerializeToString,
            ),
            'GetMemoryUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryUsage,
                    request_deserializer=worker__service__pb2.TaskIdRequest.FromString,
                    response_serializer=worker__service__pb2.MemoryUsageResponse.SerializeToString,
            ),
            'GetAllTaskIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTaskIds,
                    request_deserializer=worker__service__pb2.Empty.FromString,
                    response_serializer=worker__service__pb2.TaskIdsResponse.SerializeToString,
            ),
            'ClearTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearTask,
                    request_deserializer=worker__service__pb2.TaskIdRequest.FromString,
                    response_serializer=worker__service__pb2.MessageResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=worker__service__pb2.TaskIdRequest.FromString,
                    response_serializer=worker__service__pb2.MessageResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=worker__service__pb2.Empty.FromString,
                    response_serializer=worker__service__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flowfile.worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flowfile.worker.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Worker service for dataframe processing operations
    """

    @staticmethod
    def SubmitQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/SubmitQuery',
            worker__service__pb2.SubmitQueryRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/StoreSample',
            worker__service__pb2.StoreSampleRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFuzzyJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/AddFuzzyJoin',
            worker__service__pb2.FuzzyJoinRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/CreateTable',
            worker__service__pb2.CreateTableRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreDatabaseReadResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/StoreDatabaseReadResult',
            worker__service__pb2.DatabaseReadRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreDatabaseWriteResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/StoreDatabaseWriteResult',
            worker__service__pb2.DatabaseWriteRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteDataToCloud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/WriteDataToCloud',
            worker__service__pb2.CloudStorageWriteRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/WriteResults',
            worker__service__pb2.WriteResultsRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/GetStatus',
            worker__service__pb2.TaskIdRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/flowfile.worker.WorkerService/StreamStatus',
            worker__service__pb2.TaskIdRequest.SerializeToString,
            worker__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/FetchResults',
            worker__service__pb2.TaskIdRequest.SerializeToString,
            worker__service__pb2.FetchResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/GetMemoryUsage',
            worker__service__pb2.TaskIdRequest.SerializeToString,
            worker__service__pb2.MemoryUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllTaskIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/GetAllTaskIds',
            worker__service__pb2.Empty.SerializeToString,
            worker__service__pb2.TaskIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/ClearTask',
            worker__service__pb2.TaskIdRequest.SerializeToString,
            worker__service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/CancelTask',
            worker__service__pb2.TaskIdRequest.SerializeToString,
            worker__service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.WorkerService/Shutdown',
            worker__service__pb2.Empty.SerializeToString,
            worker__service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LoggingServiceStub(object):
    """Logging service for worker -> core communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLog = channel.unary_unary(
                '/flowfile.worker.LoggingService/SendLog',
                request_serializer=worker__service__pb2.LogEntry.SerializeToString,
                response_deserializer=worker__service__pb2.LogResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.stream_unary(
                '/flowfile.worker.LoggingService/StreamLogs',
                request_serializer=worker__service__pb2.LogEntry.SerializeToString,
                response_deserializer=worker__service__pb2.LogResponse.FromString,
                _registered_method=True)


class LoggingServiceServicer(object):
    """Logging service for worker -> core communication
    """

    def SendLog(self, request, context):
        """Send a single log entry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request_iterator, context):
        """Stream log entries (client streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendLog': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLog,
                    request_deserializer=worker__service__pb2.LogEntry.FromString,
                    response_serializer=worker__service__pb2.LogResponse.SerializeToString,
            ),
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=worker__service__pb2.LogEntry.FromString,
                    response_serializer=worker__service__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flowfile.worker.LoggingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flowfile.worker.LoggingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoggingService(object):
    """Logging service for worker -> core communication
    """

    @staticmethod
    def SendLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowfile.worker.LoggingService/SendLog',
            worker__service__pb2.LogEntry.SerializeToString,
            worker__service__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/flowfile.worker.LoggingService/StreamLogs',
            worker__service__pb2.LogEntry.SerializeToString,
            worker__service__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
