# Auto-generated stub for flowfile_frame.catalog — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from flowfile_frame.catalog_reference import WriteMode
from flowfile_core.flowfile.flow_graph import FlowGraph
from flowfile_frame.catalog_reference import SchemaReference
from flowfile_frame.flow_frame import FlowFrame

def get_current_user_id() -> int: ...
def add_write_to_catalog(flow_graph: FlowGraph, depends_on_node_id: int, *, table_name: str, schema: SchemaReference | None=None, namespace_id: int | None=None, write_mode: str='overwrite', merge_keys: list[str] | None=None, description: str | None=None) -> int: ...
def read_catalog_table(table_name: str, *, schema: SchemaReference | None=None, namespace_id: int | None=None, delta_version: int | None=None, flow_graph: FlowGraph | None=None) -> FlowFrame: ...
def read_catalog_sql(sql_query: str, *, flow_graph: FlowGraph | None=None) -> FlowFrame: ...
def write_catalog_table(df: FlowFrame, table_name: str, *, schema: SchemaReference | None=None, namespace_id: int | None=None, write_mode: WriteMode='overwrite', merge_keys: list[str] | None=None, description: str | None=None) -> None: ...
def save_flow_to_catalog(flow_or_frame: FlowFrame | FlowGraph, name: str, *, schema: SchemaReference | None=None, description: str | None=None) -> int: ...
