# This file was auto-generated to provide type information for flowfile_frame.expr_name
# DO NOT MODIFY THIS FILE MANUALLY
# Run `python flowfile_frame/submodule_stub_generator.py` to regenerate
from __future__ import annotations

from typing import Any, Callable, Iterable, Optional, Union

from collections.abc import Callable
from typing import TYPE_CHECKING
from flowfile_frame.expr import Expr
import inspect

class ExprNameNameSpace:
    def __init__(self, parent_expr: Expr, parent_repr_str: str) -> Any: ...
    def keep(self) -> Expr: ...
    def map(self, function: Callable[[str], str]) -> Expr: ...
    def map_fields(self, function: Callable[[str], str]) -> Expr: ...
    def prefix(self, prefix: str) -> Expr: ...
    def prefix_fields(self, prefix: str) -> Expr: ...
    def suffix(self, suffix: str) -> Expr: ...
    def suffix_fields(self, suffix: str) -> Expr: ...
    def to_lowercase(self) -> Expr: ...
    def to_uppercase(self) -> Expr: ...

