# Auto-generated stub for flowfile_frame.expr_name — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from collections.abc import Callable
from flowfile_frame.expr import Expr
from typing import Any

class ExprNameNameSpace:
    def __init__(self, parent_expr: Expr, parent_repr_str: str) -> Any: ...
    def keep(self) -> Expr: ...
    def map(self, function: Callable[[str], str]) -> Expr: ...
    def prefix(self, prefix: str) -> Expr: ...
    def suffix(self, suffix: str) -> Expr: ...
    def to_lowercase(self) -> Expr: ...
    def to_uppercase(self) -> Expr: ...
    def map_fields(self, function: Callable[[str], str]) -> Expr: ...
    def prefix_fields(self, prefix: str) -> Expr: ...
    def suffix_fields(self, suffix: str) -> Expr: ...

