# Auto-generated stub for flowfile_frame.flow_frame_methods — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any, Literal
from polars._typing import IO, CsvEncoding, PolarsDataType, SchemaDict, Sequence
from flowfile_core.flowfile.flow_graph import FlowGraph
from flowfile_core.schemas import input_schema
from flowfile_frame.flow_frame import FlowFrame

def sum(expr) -> Any: ...
def mean(expr) -> Any: ...
def min(expr) -> Any: ...
def max(expr) -> Any: ...
def count(expr) -> Any: ...
def read_csv(source: str | Path | IO[bytes] | bytes | list[str | Path | IO[bytes] | bytes], *, flow_graph: Any | None=None, separator: str=',', convert_to_absolute_path: bool=True, description: str | None=None, has_header: bool=True, new_columns: list[str] | None=None, comment_prefix: str | None=None, quote_char: str | None='"', skip_rows: int=0, skip_lines: int=0, schema: SchemaDict | None=None, schema_overrides: SchemaDict | Sequence[PolarsDataType] | None=None, null_values: str | list[str] | dict[str, str] | None=None, missing_utf8_is_empty_string: bool=False, ignore_errors: bool=False, try_parse_dates: bool=False, infer_schema: bool=True, infer_schema_length: int | None=100, n_rows: int | None=None, encoding: CsvEncoding='utf8', low_memory: bool=False, rechunk: bool=False, storage_options: dict[str, Any] | None=None, skip_rows_after_header: int=0, row_index_name: str | None=None, row_index_offset: int=0, eol_char: str='\n', raise_if_empty: bool=True, truncate_ragged_lines: bool=False, decimal_comma: bool=False, glob: bool=True, cache: bool=True, with_column_names: Callable[[list[str]], list[str]] | None=None, **other_options: Any) -> FlowFrame: ...
def read_parquet(source, *, flow_graph: FlowGraph=None, description: str=None, convert_to_absolute_path: bool=True, **options) -> FlowFrame: ...
def read_excel(source, *, sheet_name: str | None=None, has_header: bool=True, flow_graph: FlowGraph=None, description: str=None, convert_to_absolute_path: bool=True) -> FlowFrame: ...
def from_dict(data, *, flow_graph: FlowGraph=None, description: str=None) -> FlowFrame: ...
def from_raw_data(raw_data: input_schema.RawData, *, flow_graph: FlowGraph=None, description: str=None) -> FlowFrame: ...
def concat(frames: list['FlowFrame'], how: str='vertical', rechunk: bool=False, parallel: bool=True, description: str=None) -> 'FlowFrame': ...
def scan_csv(source: str | Path | IO[bytes] | bytes | list[str | Path | IO[bytes] | bytes], *, flow_graph: Any | None=None, separator: str=',', convert_to_absolute_path: bool=True, description: str | None=None, has_header: bool=True, new_columns: list[str] | None=None, comment_prefix: str | None=None, quote_char: str | None='"', skip_rows: int=0, skip_lines: int=0, schema: SchemaDict | None=None, schema_overrides: SchemaDict | Sequence[PolarsDataType] | None=None, null_values: str | list[str] | dict[str, str] | None=None, missing_utf8_is_empty_string: bool=False, ignore_errors: bool=False, try_parse_dates: bool=False, infer_schema: bool=True, infer_schema_length: int | None=100, n_rows: int | None=None, encoding: CsvEncoding='utf8', low_memory: bool=False, rechunk: bool=False, storage_options: dict[str, Any] | None=None, skip_rows_after_header: int=0, row_index_name: str | None=None, row_index_offset: int=0, eol_char: str='\n', raise_if_empty: bool=True, truncate_ragged_lines: bool=False, decimal_comma: bool=False, glob: bool=True, cache: bool=True, with_column_names: Callable[[list[str]], list[str]] | None=None, **other_options: Any) -> FlowFrame: ...
def scan_parquet(source, *, flow_graph: FlowGraph=None, description: str=None, convert_to_absolute_path: bool=True, **options) -> FlowFrame: ...
def scan_parquet_from_cloud_storage(source: str, *, flow_graph: FlowGraph | None=None, connection_name: str | None=None, scan_mode: Literal['single_file', 'directory', None]=None, description: str | None=None, output_field_config: input_schema.OutputFieldConfig | None=None) -> FlowFrame: ...
def scan_csv_from_cloud_storage(source: str, *, flow_graph: FlowGraph | None=None, connection_name: str | None=None, scan_mode: Literal['single_file', 'directory', None]=None, delimiter: str=';', has_header: bool | None=True, encoding: CsvEncoding | None='utf8', output_field_config: input_schema.OutputFieldConfig | None=None) -> FlowFrame: ...
def scan_delta(source: str, *, flow_graph: FlowGraph | None=None, connection_name: str | None=None, version: int=None, output_field_config: input_schema.OutputFieldConfig | None=None) -> FlowFrame: ...
def scan_json_from_cloud_storage(source: str, *, flow_graph: FlowGraph | None=None, connection_name: str | None=None, scan_mode: Literal['single_file', 'directory', None]=None, output_field_config: input_schema.OutputFieldConfig | None=None) -> FlowFrame: ...
