# Auto-generated stub for flowfile_frame.flow_group — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from flowfile_core.schemas.schemas import GroupColor
from flowfile_core.flowfile.flow_graph import FlowGraph
from typing import Any

class FlowGroup:
    def __init__(self, name: str='Group', *, color: GroupColor | None=None, parent_group: FlowGroup | None=None) -> Any: ...
    @property
    def name(self) -> str: ...
    @property
    def color(self) -> GroupColor | None: ...
    @property
    def parent_group(self) -> FlowGroup | None: ...
    @property
    def flow_graph(self) -> FlowGraph | None: ...
    @property
    def id(self) -> int | None: ...
    @property
    def node_ids(self) -> list[int]: ...


def rebind_groups(old_graphs, combined: FlowGraph, group_id_mapping: dict[tuple[int, int], int]) -> None: ...
