# This file was auto-generated to provide type information for flowfile_frame.group_frame
# DO NOT MODIFY THIS FILE MANUALLY
# Run `python flowfile_frame/submodule_stub_generator.py` to regenerate
from __future__ import annotations

from typing import Any, Callable, Iterable, Optional, Union

from typing import TYPE_CHECKING, Any
from flowfile_core.schemas import input_schema, transform_schema
from flowfile_frame.expr import Column, Expr, col, lit
from flowfile_frame.selectors import Selector
from flowfile_frame.utils import _check_if_convertible_to_code, _parse_inputs_as_iterable, ensure_inputs_as_iterable, get_pl_expr_from_expr
from flowfile_frame.flow_frame import FlowFrame

class GroupByFrame:
    def __init__(self, node_id: int, parent_frame, by_cols, maintain_order=False, description: str=None) -> Any: ...
    def agg(self, *agg_exprs, **named_agg_exprs) -> None: ...
    def count(self) -> FlowFrame: ...
    def first(self) -> Any: ...
    def head(self, n: int=10) -> Any: ...
    def last(self) -> Any: ...
    def len(self) -> FlowFrame: ...
    def max(self) -> Any: ...
    def mean(self) -> Any: ...
    def median(self) -> Any: ...
    def min(self) -> Any: ...
    def readable_group(self) -> Any: ...
    def sum(self) -> Any: ...
    def tail(self, n: int=10) -> Any: ...

