# Auto-generated stub for flowfile_frame.group_frame — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from typing import Any
from flowfile_frame.flow_frame import FlowFrame

class GroupByFrame:
    def __init__(self, node_id: int, parent_frame, by_cols, maintain_order=False, description: str=None) -> Any: ...
    def readable_group(self) -> Any: ...
    def len(self) -> 'FlowFrame': ...
    def count(self) -> 'FlowFrame': ...
    def agg(self, *agg_exprs, **named_agg_exprs) -> FlowFrame: ...
    def sum(self) -> Any: ...
    def mean(self) -> Any: ...
    def median(self) -> Any: ...
    def min(self) -> Any: ...
    def max(self) -> Any: ...
    def tail(self, n: int=10) -> Any: ...
    def head(self, n: int=10) -> Any: ...
    def first(self) -> Any: ...
    def last(self) -> Any: ...

