# This file was auto-generated to provide type information for flowfile_frame.list_name_space
# DO NOT MODIFY THIS FILE MANUALLY
# Run `python flowfile_frame/submodule_stub_generator.py` to regenerate
from __future__ import annotations

from typing import Any, Callable, Iterable, Optional, Union

from collections.abc import Callable, Sequence
from typing import TYPE_CHECKING, Any
import polars as pl
from datetime import date, datetime, time
from polars._typing import IntoExprColumn, ListToStructWidthStrategy, NullBehavior
from flowfile_frame.expr import Expr

class ExprListNameSpace:
    def __init__(self, parent_expr: Expr, parent_repr_str: str) -> Any: ...
    def all(self) -> Expr: ...
    def any(self) -> Expr: ...
    def arg_max(self) -> Expr: ...
    def arg_min(self) -> Expr: ...
    def concat(self, other: list[Expr | str] | Expr | str | pl.Series | list[Any]) -> Expr: ...
    def contains(self, item: float | str | bool | int | date | datetime | time | IntoExprColumn) -> Expr: ...
    def count_matches(self, element: Any) -> Expr: ...
    def diff(self, n: int=1, null_behavior: NullBehavior='ignore') -> Expr: ...
    def drop_nulls(self) -> Expr: ...
    def eval(self, expr: Expr, parallel: bool=False) -> Expr: ...
    def explode(self) -> Expr: ...
    def first(self) -> Expr: ...
    def gather(self, indices: Expr | pl.Series | list[int] | list[list[int]], null_on_oob: bool=False) -> Expr: ...
    def gather_every(self, n: int | IntoExprColumn, offset: int | IntoExprColumn=0) -> Expr: ...
    def get(self, index: int | Expr | str, null_on_oob: bool=False) -> Expr: ...
    def head(self, n: int | str | Expr=5) -> Expr: ...
    def join(self, separator: IntoExprColumn, ignore_nulls: bool=True) -> Expr: ...
    def last(self) -> Expr: ...
    def len(self) -> Expr: ...
    def max(self) -> Expr: ...
    def mean(self) -> Expr: ...
    def median(self) -> Expr: ...
    def min(self) -> Expr: ...
    def n_unique(self) -> Expr: ...
    def reverse(self) -> Expr: ...
    def sample(self, n: int | IntoExprColumn | None=None, fraction: float | IntoExprColumn | None=None, with_replacement: bool=False, shuffle: bool=False, seed: int | None=None) -> Expr: ...
    def set_difference(self, other: Any) -> Expr: ...
    def set_intersection(self, other: Any) -> Expr: ...
    def set_symmetric_difference(self, other: Any) -> Expr: ...
    def set_union(self, other: Any) -> Expr: ...
    def shift(self, n: int | IntoExprColumn=1) -> Expr: ...
    def slice(self, offset: int | str | Expr, length: int | str | Expr | None=None) -> Expr: ...
    def sort(self, descending: bool=False, nulls_last: bool=False) -> Expr: ...
    def std(self, ddof: int=1) -> Expr: ...
    def sum(self) -> Expr: ...
    def tail(self, n: int | str | Expr=5) -> Expr: ...
    def to_array(self, width: int) -> Expr: ...
    def to_struct(self, n_field_strategy: ListToStructWidthStrategy='first_non_null', fields: Sequence[str] | Callable[[int], str] | None=None, upper_bound: int=0) -> Expr: ...
    def unique(self, maintain_order: bool=False) -> Expr: ...
    def var(self, ddof: int=1) -> Expr: ...

