# Auto-generated stub for flowfile_frame.parameters — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from typing import Any
import polars as pl
from flowfile_core.flowfile.flow_graph import FlowGraph
from flowfile_core.flowfile.param_types import FlowParameter, ParamValue
from flowfile_frame.enums import ParamType, ParamTypeLiteral
from flowfile_frame.expr import Expr
from flowfile_frame.flow_frame import FlowFrame

class Parameter:
    model: FlowParameter
    def __init__(self, name: str, *, default: Any='', type: ParamTypeLiteral | ParamType='string', description: str='', enum_values: list[str] | None=None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> ParamTypeLiteral: ...
    @property
    def default(self) -> ParamValue: ...
    @property
    def dtype(self) -> pl.DataType: ...
    @property
    def ref(self) -> str: ...
    def to_expr(self) -> Expr: ...


def refuse_parameter_as_column(value: Any, where: str) -> None: ...
def refuse_parameter_column_in_formula(formula: str | None, where: str) -> None: ...
def add_flow_parameter(flow: FlowGraph | FlowFrame, parameter: Parameter) -> Parameter: ...
def set_flow_parameter(flow: FlowGraph | FlowFrame, name: str | Parameter, value: Any) -> None: ...
