# This file was auto-generated to provide type information for flowfile_frame.selectors
# DO NOT MODIFY THIS FILE MANUALLY
# Run `python flowfile_frame/submodule_stub_generator.py` to regenerate
from __future__ import annotations

from typing import Any, Callable, Iterable, Optional, Union

import polars as pl
from flowfile_frame.expr import Expr

class Selector:
    def __init__(self) -> Any: ...
    def count(self) -> Expr: ...
    def expr(self) -> Any: ...
    def first(self) -> Expr: ...
    def last(self) -> Expr: ...
    def max(self) -> Expr: ...
    def mean(self) -> Expr: ...
    def median(self) -> Expr: ...
    def min(self) -> Expr: ...
    def n_unique(self) -> Expr: ...
    @property
    def repr_str(self) -> Any: ...
    def std(self, ddof: int=1) -> Expr: ...
    def sum(self) -> Expr: ...
    def var(self, ddof: int=1) -> Expr: ...

class StringSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class StructSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class TemporalSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class TimeSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class AllSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class BooleanSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class CategoricalSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class ComplementSelector(Selector):
    def __init__(self, selector: Selector) -> Any: ...
    @property
    def repr_str(self) -> Any: ...

class CompoundSelector(Selector):
    def __init__(self, left: Selector, right: Selector, operation: str) -> Any: ...
    @property
    def repr_str(self) -> Any: ...

class DateSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class DatetimeSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class DtypeSelector(Selector):
    def __init__(self, dtypes: pl.DataType | list[pl.DataType]) -> Any: ...
    @property
    def repr_str(self) -> Any: ...

class DurationSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class FloatSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class IntegerSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class ListSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class NumericSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class ObjectSelector(Selector):
    @property
    def repr_str(self) -> Any: ...

class PatternSelector(Selector):
    def __init__(self, pattern: str) -> Any: ...
    @property
    def repr_str(self) -> Any: ...

class StartsWithSelector(PatternSelector):
    @property
    def repr_str(self) -> Any: ...

class ContainsSelector(PatternSelector):
    @property
    def repr_str(self) -> Any: ...

class EndsWithSelector(PatternSelector):
    @property
    def repr_str(self) -> Any: ...

class MatchesSelector(PatternSelector):
    @property
    def repr_str(self) -> Any: ...

def all_() -> AllSelector: ...

def boolean() -> BooleanSelector: ...

def by_dtype(dtypes: pl.DataType | list[pl.DataType]) -> DtypeSelector: ...

def categorical() -> CategoricalSelector: ...

def contains(pattern: str) -> ContainsSelector: ...

def date() -> DateSelector: ...

def datetime() -> DatetimeSelector: ...

def duration() -> DurationSelector: ...

def ends_with(pattern: str) -> EndsWithSelector: ...

def float_() -> FloatSelector: ...

def integer() -> IntegerSelector: ...

def list_() -> ListSelector: ...

def matches(pattern: str) -> MatchesSelector: ...

def numeric() -> NumericSelector: ...

def object_() -> ObjectSelector: ...

def starts_with(pattern: str) -> StartsWithSelector: ...

def string() -> StringSelector: ...

def struct() -> StructSelector: ...

def temporal() -> TemporalSelector: ...

def time() -> TimeSelector: ...

