# Auto-generated stub for flowfile_frame.selectors — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

import polars as pl
from flowfile_frame.expr import Expr
from typing import Any

class Selector:
    def __init__(self) -> Any: ...
    @property
    def repr_str(self) -> Any: ...
    def sum(self) -> 'Expr': ...
    def expr(self) -> Any: ...
    def mean(self) -> 'Expr': ...
    def median(self) -> 'Expr': ...
    def min(self) -> 'Expr': ...
    def max(self) -> 'Expr': ...
    def std(self, ddof: int=1) -> 'Expr': ...
    def var(self, ddof: int=1) -> 'Expr': ...
    def first(self) -> 'Expr': ...
    def last(self) -> 'Expr': ...
    def count(self) -> 'Expr': ...
    def n_unique(self) -> 'Expr': ...

class CompoundSelector(Selector):
    def __init__(self, left: Selector, right: Selector, operation: str) -> Any: ...

class ComplementSelector(Selector):
    def __init__(self, selector: Selector) -> Any: ...

class NumericSelector(Selector):
    ...

class FloatSelector(Selector):
    ...

class IntegerSelector(Selector):
    ...

class StringSelector(Selector):
    ...

class TemporalSelector(Selector):
    ...

class DatetimeSelector(Selector):
    ...

class DateSelector(Selector):
    ...

class TimeSelector(Selector):
    ...

class DurationSelector(Selector):
    ...

class BooleanSelector(Selector):
    ...

class CategoricalSelector(Selector):
    ...

class ObjectSelector(Selector):
    ...

class ListSelector(Selector):
    ...

class StructSelector(Selector):
    ...

class AllSelector(Selector):
    ...

class DtypeSelector(Selector):
    def __init__(self, dtypes: pl.DataType | list[pl.DataType]) -> Any: ...

class PatternSelector(Selector):
    def __init__(self, pattern: str) -> Any: ...

class ContainsSelector(PatternSelector):
    ...

class StartsWithSelector(PatternSelector):
    ...

class EndsWithSelector(PatternSelector):
    ...

class MatchesSelector(PatternSelector):
    ...


def numeric() -> NumericSelector: ...
def float_() -> FloatSelector: ...
def integer() -> IntegerSelector: ...
def string() -> StringSelector: ...
def temporal() -> TemporalSelector: ...
def datetime() -> DatetimeSelector: ...
def date() -> DateSelector: ...
def time() -> TimeSelector: ...
def duration() -> DurationSelector: ...
def boolean() -> BooleanSelector: ...
def categorical() -> CategoricalSelector: ...
def object_() -> ObjectSelector: ...
def list_() -> ListSelector: ...
def struct() -> StructSelector: ...
def all_() -> AllSelector: ...
def by_dtype(dtypes: pl.DataType | list[pl.DataType]) -> DtypeSelector: ...
def contains(pattern: str) -> ContainsSelector: ...
def starts_with(pattern: str) -> StartsWithSelector: ...
def ends_with(pattern: str) -> EndsWithSelector: ...
def matches(pattern: str) -> MatchesSelector: ...
