# Auto-generated stub for flowfile_frame.utils — do not edit.
# Run `make stubs` to regenerate from the Python source.
from __future__ import annotations

from collections.abc import Iterable
from typing import Any
import polars as pl
from flowfile_core.flowfile.flow_graph import FlowGraph

def get_pl_expr_from_expr(expr: Any) -> pl.Expr: ...
def ensure_inputs_as_iterable(inputs: Any | Iterable[Any]) -> list[Any]: ...
def create_flow_graph(flow_id: int=None) -> FlowGraph: ...
def stringify_values(v: Any) -> str: ...
def generate_node_id() -> int: ...
def set_node_id(node_id) -> Any: ...
