"""File, cloud and catalog IO nodes.

Generated from the pre-registry catalogs (NodeTemplate list, settings map,
AI classification map); maintained by hand from here on.
"""

from flowfile_core.flowfile.node_registry.spec import NodeSpec
from flowfile_core.schemas import input_schema
from flowfile_core.schemas.schemas import NodeTag, NodeTemplate

SPECS: list[NodeSpec] = [
    NodeSpec(
        node_type="api_response",
        settings_class=input_schema.NodeApiResponse,
        template=NodeTemplate(
            name="API response",
            item="api_response",
            input=1,
            output=0,
            image="api_response.svg",
            node_type="output",
            transform_type="other",
            node_group="output",
            drawer_title="API Response",
            drawer_intro="Return this dataset as the body of an HTTP API endpoint",
            tags=[NodeTag.API, NodeTag.REST, NodeTag.HTTP, NodeTag.RESPONSE],
        ),
        ai_classification="static",
    ),
    NodeSpec(
        node_type="explore_data",
        settings_class=input_schema.NodeExploreData,
        template=NodeTemplate(
            name="Explore data",
            item="explore_data",
            input=1,
            output=0,
            image="explore_data.svg",
            node_type="output",
            transform_type="other",
            node_group="output",
            drawer_title="Explore Data",
            drawer_intro="Interactive data exploration and analysis",
            tags=[
                NodeTag.EXPLORE,
                NodeTag.PROFILE,
                NodeTag.PREVIEW,
                NodeTag.EDA,
                NodeTag.STATISTICS,
                NodeTag.VISUALIZE,
                NodeTag.INSIGHT,
                NodeTag.BAR_CHART,
                NodeTag.GRAPHS,
            ],
        ),
        ai_classification="static",
    ),
    NodeSpec(
        node_type="manual_input",
        settings_class=input_schema.NodeManualInput,
        template=NodeTemplate(
            name="Manual input",
            item="manual_input",
            input=0,
            output=1,
            image="manual_input.svg",
            node_type="input",
            transform_type="other",
            node_group="input",
            drawer_title="Manual Input",
            drawer_intro="Create data directly",
            laziness="lazy",
            tags=[NodeTag.MANUAL, NodeTag.PASTE, NodeTag.INPUT],
        ),
        ai_classification="source",
    ),
    NodeSpec(
        node_type="read",
        settings_class=input_schema.NodeRead,
        template=NodeTemplate(
            name="Read data",
            item="read",
            input=0,
            output=1,
            image="input_data.svg",
            node_type="input",
            transform_type="other",
            node_group="input",
            drawer_title="Read Data",
            drawer_intro="Load data from CSV, Excel, or Parquet files",
            laziness="conditional",
            tags=[
                NodeTag.CSV,
                NodeTag.EXCEL,
                NodeTag.PARQUET,
                NodeTag.JSON,
                NodeTag.FILE,
                NodeTag.IMPORT,
                NodeTag.READ,
            ],
        ),
        ai_classification="source",
    ),
    NodeSpec(
        node_type="catalog_reader",
        settings_class=input_schema.NodeCatalogReader,
        template=NodeTemplate(
            name="Read from Catalog",
            item="catalog_reader",
            input=0,
            output=1,
            image="catalog_reader.svg",
            node_type="input",
            transform_type="other",
            node_group="input",
            drawer_title="Catalog Reader",
            drawer_intro="Read a table from the data catalog",
            laziness="lazy",
            tags=[NodeTag.CATALOG, NodeTag.DELTA, NodeTag.TABLE, NodeTag.LAKEHOUSE, NodeTag.TIME_TRAVEL],
        ),
        ai_classification="source",
    ),
    NodeSpec(
        node_type="cloud_storage_reader",
        settings_class=input_schema.NodeCloudStorageReader,
        template=NodeTemplate(
            name="Read from cloud provider",
            item="cloud_storage_reader",
            input=0,
            output=1,
            image="cloud_storage_reader.svg",
            node_type="input",
            transform_type="other",
            node_group="input",
            drawer_title="Cloud Storage Reader",
            drawer_intro="Read data from AWS S3 and other cloud storage",
            laziness="conditional",
            tags=[
                NodeTag.S3,
                NodeTag.AWS,
                NodeTag.AZURE,
                NodeTag.ADLS,
                NodeTag.GCS,
                NodeTag.BLOB,
                NodeTag.BUCKET,
                NodeTag.CLOUD,
                NodeTag.DELTA,
            ],
        ),
        ai_classification="source",
    ),
    NodeSpec(
        node_type="output",
        settings_class=input_schema.NodeOutput,
        template=NodeTemplate(
            name="Write data",
            item="output",
            input=1,
            output=0,
            image="output.svg",
            node_type="output",
            transform_type="other",
            node_group="output",
            drawer_title="Write Data",
            drawer_intro="Save your data as CSV, Excel, or Parquet files",
            tags=[
                NodeTag.CSV,
                NodeTag.EXCEL,
                NodeTag.PARQUET,
                NodeTag.JSON,
                NodeTag.FILE,
                NodeTag.EXPORT,
                NodeTag.SAVE,
                NodeTag.WRITE,
            ],
        ),
        ai_classification="static",
    ),
    NodeSpec(
        node_type="catalog_writer",
        settings_class=input_schema.NodeCatalogWriter,
        template=NodeTemplate(
            name="Write to Catalog",
            item="catalog_writer",
            input=1,
            output=0,
            image="catalog_writer.svg",
            node_type="output",
            transform_type="other",
            node_group="output",
            drawer_title="Catalog Writer",
            drawer_intro="Save data as a table in the data catalog",
            tags=[NodeTag.CATALOG, NodeTag.DELTA, NodeTag.TABLE, NodeTag.LAKEHOUSE],
        ),
        ai_classification="static",
    ),
    NodeSpec(
        node_type="cloud_storage_writer",
        settings_class=input_schema.NodeCloudStorageWriter,
        template=NodeTemplate(
            name="Write to cloud provider",
            item="cloud_storage_writer",
            input=1,
            output=0,
            image="cloud_storage_writer.svg",
            node_type="output",
            transform_type="other",
            node_group="output",
            drawer_title="Cloud Storage Writer",
            drawer_intro="Save data to AWS S3 and other cloud storage",
            tags=[
                NodeTag.S3,
                NodeTag.AWS,
                NodeTag.AZURE,
                NodeTag.ADLS,
                NodeTag.GCS,
                NodeTag.BLOB,
                NodeTag.BUCKET,
                NodeTag.CLOUD,
                NodeTag.DELTA,
            ],
        ),
        ai_classification="static",
    ),
]
