"""Generate the Flowfile formula-function reference page from the live engine.

The ``[column]`` formula functions are defined in the ``polars_expr_transformer``
package (Flowfile's formula engine). Rather than hand-maintaining a list that
drifts from the package, this script asks the engine for its own function
catalog via ``get_expression_overview()`` and renders a categorized Markdown
reference.

Run it whenever the engine version changes::

    python scripts/gen_formula_reference.py

Output: ``docs/users/python-api/reference/formula-functions.md`` (committed).
It can also be wired into ``mkdocs.yml`` as a build hook so it always stays
fresh; see ``docs`` build setup.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from polars_expr_transformer import get_expression_overview

# Human-friendly section titles + ordering for the engine's category keys.
CATEGORY_TITLES: dict[str, str] = {
    "logic": "Logic & comparison",
    "string": "String",
    "math": "Math",
    "date": "Date & time",
    "type_conversions": "Type conversion",
}
CATEGORY_ORDER = ["logic", "string", "math", "date", "type_conversions"]

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "docs"
    / "users"
    / "python-api"
    / "reference"
    / "formula-functions.md"
)


def _parse_doc(doc: str) -> tuple[str, str]:
    """Return ``(summary, example)`` extracted from an ExpressionRef docstring."""
    lines = [line.strip() for line in textwrap.dedent(doc or "").strip().splitlines()]
    summary = ""
    example = ""
    for line in lines:
        if not summary and line:
            summary = line
        if line.lower().startswith("for example"):
            # "For example, length(\"hello\") would return 5." -> keep the sentence.
            example = line.split(",", 1)[1].strip() if "," in line else line
            break
    return summary, example


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def render() -> str:
    overview = {ov.expression_type: ov for ov in get_expression_overview()}
    total = sum(len(ov.expressions) for ov in overview.values())

    out: list[str] = []
    out.append("<!-- AUTO-GENERATED by scripts/gen_formula_reference.py — do not edit by hand. -->")
    out.append("")
    out.append("# Formula function reference")
    out.append("")
    out.append(
        "Every function available inside Flowfile's `[column]` "
        "[formula syntax](../concepts/expressions.md). These power the "
        "`flowfile_formula` / `flowfile_formulas` parameters on `filter` and "
        "`with_columns`, and the formula bar in the visual editor."
    )
    out.append("")
    out.append(
        f"There are **{total}** functions across {len(CATEGORY_ORDER)} categories. "
        "Use them with bracketed column references, e.g. `uppercase([name])` or "
        "`round([price] * [qty], 2)`."
    )
    out.append("")

    for key in CATEGORY_ORDER:
        ov = overview.get(key)
        if ov is None or not ov.expressions:
            continue
        out.append(f"## {CATEGORY_TITLES.get(key, key.title())}")
        out.append("")
        out.append("| Function | What it does | Example |")
        out.append("| --- | --- | --- |")
        for expr in sorted(ov.expressions, key=lambda e: e.name):
            summary, example = _parse_doc(expr.doc)
            example_cell = f"`{example.rstrip('.')}`" if example else ""
            out.append(f"| `{expr.name}` | {_escape(summary)} | {_escape(example_cell)} |")
        out.append("")

    out.append("---")
    out.append("")
    out.append(
        "!!! note \"Fuzzy string matching\"\n"
        "    String-similarity functions (Levenshtein, Jaro-Winkler, etc.) require the "
        "optional `polars-ds` dependency and are not available in the browser playground."
    )
    out.append("")
    return "\n".join(out)


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
