"""Project manifest + generated ``.gitignore`` load/save."""

from __future__ import annotations

import uuid
from pathlib import Path

from flowfile_core.workspace.layout import ProjectLayout
from flowfile_core.workspace.models import ProjectManifest
from flowfile_core.workspace.normalize import canonical_yaml_dump, canonical_yaml_load

# Things that must never be versioned: the runtime DB, secret values, the master
# key, materialized data, and the local sync-state fingerprints.
_GITIGNORE_LINES = [
    "# Generated by Flowfile -- do not commit runtime / secret artifacts.",
    ".flowfile/",
    "*.db",
    "*.db-journal",
    "*.db-wal",
    "*.db-shm",
    "data/",
    "catalog_tables/",
    "master.key",
    "master_key.txt",
    ".env",
    "**/secrets/*.value",
]


def load_manifest(layout: ProjectLayout) -> ProjectManifest | None:
    path = layout.manifest_path
    if not path.exists():
        return None
    data = canonical_yaml_load(path.read_text(encoding="utf-8"))
    return ProjectManifest.model_validate(data)


def save_manifest(layout: ProjectLayout, manifest: ProjectManifest) -> None:
    layout.root.mkdir(parents=True, exist_ok=True)
    text = canonical_yaml_dump(manifest.model_dump(mode="json"))
    layout.manifest_path.write_text(text, encoding="utf-8")


def write_gitignore(layout: ProjectLayout) -> None:
    text = "\n".join(_GITIGNORE_LINES) + "\n"
    layout.gitignore_path.write_text(text, encoding="utf-8")


def init_project(root: str | Path, name: str, *, namespace_roots: list[str] | None = None) -> ProjectManifest:
    """Create a fresh project tree (manifest + .gitignore + dirs).

    Idempotent: re-initializing an existing project keeps its ``project_id`` and
    refreshes the manifest/.gitignore.
    """
    from flowfile_core import __version__

    layout = ProjectLayout(root)
    existing = load_manifest(layout)
    project_id = existing.project_id if existing else str(uuid.uuid4())

    manifest = ProjectManifest(
        flowfile_version=__version__,
        project_id=project_id,
        name=name,
        namespace_roots=namespace_roots or (existing.namespace_roots if existing else []),
    )
    layout.root.mkdir(parents=True, exist_ok=True)
    for sub in (layout.flows_dir, layout.connections_dir, layout.secrets_dir, layout.schedules_dir):
        sub.mkdir(parents=True, exist_ok=True)
    save_manifest(layout, manifest)
    write_gitignore(layout)
    return manifest
