import datetime
import logging
from dataclasses import dataclass, replace

import openpyxl
import polars as pl
import pytest

import shared.excel_reader as excel_reader
from shared.excel_reader import (
    FALLBACK_ENGINE,
    df_from_calamine_xlsx,
    df_from_openpyxl,
    ensure_unique,
    read_excel_table,
    select_excel_engine,
)

SHEET = "Sheet1"


@dataclass
class ExcelSettings:
    """The duck-typed slice of the Read node's excel settings that the reader actually looks at."""

    sheet_name: str = None
    start_row: int = 0
    start_column: int = 0
    end_row: int = 0
    end_column: int = 0
    has_headers: bool = True
    type_inference: bool = False


class Recorder:
    """Stand-in for a run's NodeLogger: the reader accepts anything with .info/.warning."""

    def __init__(self):
        self.info_lines = []
        self.warning_lines = []

    def info(self, message):
        self.info_lines.append(str(message))

    def warning(self, message):
        self.warning_lines.append(str(message))


def _save(tmp_path, name, fill):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = SHEET
    fill(ws)
    path = tmp_path / name
    wb.save(path)
    return str(path)


def _plain_table(tmp_path, name="plain.xlsx"):
    """A boring A1-anchored table: header row a,b followed by three data rows."""

    def fill(ws):
        ws.cell(row=1, column=1, value="a")
        ws.cell(row=1, column=2, value="b")
        for row in range(2, 5):
            ws.cell(row=row, column=1, value=row)
            ws.cell(row=row, column=2, value=row * 10)

    return _save(tmp_path, name, fill)


def _metadata_and_stray_cell(tmp_path):
    """The reported case: a metadata line above the table plus a stray note off to the right.

    Openpyxl's used range is A1:J7 while the table under the metadata is only eight columns wide.
    """

    def fill(ws):
        ws.cell(row=1, column=1, value="Report generated by Finance")
        ws.cell(row=1, column=10, value="stray note")
        for col in range(1, 9):
            ws.cell(row=3, column=col, value=f"h{col - 1}")
        for row in range(4, 8):
            for col in range(1, 9):
                ws.cell(row=row, column=col, value=(row - 4) * 8 + col)

    return _save(tmp_path, "metadata.xlsx", fill)


def _orphan_cell_below_right(tmp_path):
    """A two-column table with one orphan value parked below and to the right of it."""

    def fill(ws):
        ws.cell(row=1, column=1, value="a")
        ws.cell(row=1, column=2, value="b")
        for row in range(2, 5):
            ws.cell(row=row, column=1, value=row)
            ws.cell(row=row, column=2, value=row * 10)
        ws.cell(row=9, column=6, value="orphan")

    return _save(tmp_path, "orphan.xlsx", fill)


def _stray_cell_on_header_row(tmp_path):
    """A two-column table with a loose note sitting in column F of the header row itself."""

    def fill(ws):
        ws.cell(row=1, column=1, value="a")
        ws.cell(row=1, column=2, value="b")
        ws.cell(row=1, column=6, value="note")
        for row in range(2, 5):
            ws.cell(row=row, column=1, value=row)
            ws.cell(row=row, column=2, value=row * 10)

    return _save(tmp_path, "stray.xlsx", fill)


def _blank_interior_header_cell(tmp_path):
    """Four columns of data whose third header cell was never filled in."""

    def fill(ws):
        for col, value in ((1, "a"), (2, "b"), (4, "d")):
            ws.cell(row=1, column=col, value=value)
        for row in range(2, 5):
            for col in range(1, 5):
                ws.cell(row=row, column=col, value=row * col)

    return _save(tmp_path, "blank_interior.xlsx", fill)


def _leading_blank_header_cell(tmp_path):
    """Three columns of data whose first header cell is blank, as a row-label column often is."""

    def fill(ws):
        ws.cell(row=1, column=2, value="b")
        ws.cell(row=1, column=3, value="c")
        for row in range(2, 5):
            for col in range(1, 4):
                ws.cell(row=row, column=col, value=row * col)

    return _save(tmp_path, "leading_blank.xlsx", fill)


def _datetime_header_row(tmp_path):
    """Issue #356: a title row above a header row whose month columns are real datetimes."""

    def fill(ws):
        for col in range(1, 12):
            ws.cell(row=1, column=col, value=f"title{col}")
        header = ["Ledger"] + [datetime.datetime(2025, month, 1) for month in range(4, 13)] + ["Location"]
        for col, value in enumerate(header, start=1):
            ws.cell(row=2, column=col, value=value)
        for col in range(1, 12):
            ws.cell(row=3, column=col, value=col * 1.5)

    return _save(tmp_path, "datetime_header.xlsx", fill)


def _empty_sheet(tmp_path):
    """A workbook holding one sheet without a single cell in it."""
    return _save(tmp_path, "empty.xlsx", lambda ws: None)


@pytest.mark.parametrize(
    ("settings", "expected"),
    [
        pytest.param(ExcelSettings(type_inference=True), "openpyxl", id="type-inference"),
        pytest.param(
            ExcelSettings(type_inference=True, start_row=2, start_column=3, has_headers=False),
            "openpyxl",
            id="type-inference-wins",
        ),
        pytest.param(ExcelSettings(start_row=2, has_headers=True), "calamine", id="row-offset-with-headers"),
        pytest.param(ExcelSettings(start_row=2, has_headers=False), "xlsx2csv", id="row-offset-headerless"),
        pytest.param(ExcelSettings(has_headers=False), "xlsx2csv", id="headerless-at-a1"),
        pytest.param(ExcelSettings(has_headers=False, start_column=1), "openpyxl", id="headerless-column-offset"),
        pytest.param(ExcelSettings(start_column=1), "openpyxl", id="column-offset"),
        pytest.param(ExcelSettings(start_row=2, start_column=1), "openpyxl", id="row-and-column-offset"),
        pytest.param(ExcelSettings(), "calamine", id="defaults"),
    ],
)
def test_select_excel_engine(settings, expected):
    """Every branch of the engine picker, including the headerless row-offset xlsx2csv case."""
    assert select_excel_engine(settings) == expected


def test_fallback_engine_is_openpyxl():
    assert FALLBACK_ENGINE == "openpyxl"


def test_metadata_and_stray_cell_reads_only_the_real_table(tmp_path, caplog):
    """The reported ShapeError case: eight real columns survive a ten-cell used range."""
    path = _metadata_and_stray_cell(tmp_path)
    settings = ExcelSettings(sheet_name=SHEET, start_row=2)
    assert select_excel_engine(settings) == "calamine"

    with caplog.at_level(logging.WARNING, logger="shared.excel_reader"):
        df = read_excel_table(path, settings)

    assert df.columns == [f"h{i}" for i in range(8)]
    assert df.height == 4
    assert "ragged used range" in caplog.text


def test_metadata_and_stray_cell_with_type_inference_keeps_the_used_range(tmp_path):
    """Type inference routes to openpyxl, which reports all ten declared columns without raising."""
    path = _metadata_and_stray_cell(tmp_path)
    settings = ExcelSettings(sheet_name=SHEET, start_row=2, type_inference=True)
    assert select_excel_engine(settings) == "openpyxl"

    df = read_excel_table(path, settings)

    assert df.width == 10
    assert df.columns[:8] == [f"h{i}" for i in range(8)]
    assert df.height == 4


def test_orphan_cell_below_right_does_not_raise(tmp_path, caplog):
    """A value parked outside the table widens the used range but must not fail the read."""
    path = _orphan_cell_below_right(tmp_path)

    with caplog.at_level(logging.WARNING, logger="shared.excel_reader"):
        df = read_excel_table(path, ExcelSettings(sheet_name=SHEET))

    assert df.columns == ["a", "b", "_unnamed_column_2"]
    assert "ragged used range" in caplog.text


def test_stray_cell_on_header_row_keeps_the_names_calamine_found(tmp_path):
    """Truncating openpyxl's header positionally would be wrong here, so calamine's names win.

    The used range is six cells -- ('a', 'b', None, None, None, 'note') -- while calamine drops the
    three empty columns and keeps 'note' as a third column. Taking openpyxl's first three cells
    would name that third column from a blank cell instead of from the value backing it.
    """
    path = _stray_cell_on_header_row(tmp_path)

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET))

    assert df.columns == ["a", "b", "note"]
    assert df.height == 3


def test_blank_interior_header_cell_becomes_a_placeholder(tmp_path):
    """Matching widths let the sheet's header win; the blank cell must not become 'None'."""
    path = _blank_interior_header_cell(tmp_path)

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET))

    assert df.columns == ["a", "b", "_unnamed_column_2", "d"]
    assert "None" not in df.columns


def test_leading_blank_header_cell_becomes_a_placeholder(tmp_path):
    """A blank first header cell is placeholdered by position, not dropped."""
    path = _leading_blank_header_cell(tmp_path)

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET))

    assert df.columns == ["_unnamed_column_0", "b", "c"]


def test_datetime_header_row_keeps_its_real_names(tmp_path, caplog):
    """Issue #356 regression: matching widths still hand datetime headers back as their str()."""
    path = _datetime_header_row(tmp_path)

    with caplog.at_level(logging.WARNING, logger="shared.excel_reader"):
        df = read_excel_table(path, ExcelSettings(sheet_name=SHEET, start_row=1))

    assert df.width == 11
    assert df.columns[0] == "Ledger"
    assert df.columns[-1] == "Location"
    assert "2025-06-01 00:00:00" in df.columns
    assert not [name for name in df.columns if name.startswith("__UNNAMED__")]
    assert "ragged used range" not in caplog.text


def test_empty_sheet_reads_as_an_empty_frame(tmp_path):
    """The header read stops at a sentinel instead of raising StopIteration on an empty sheet."""
    path = _empty_sheet(tmp_path)

    assert read_excel_table(path, ExcelSettings(sheet_name=SHEET)).shape == (0, 0)
    assert read_excel_table(path, ExcelSettings(sheet_name=SHEET, type_inference=True)).shape == (0, 0)


def test_empty_sheet_via_the_engine_helpers(tmp_path):
    """Both engine entry points tolerate an empty sheet directly, not just through the dispatcher."""
    path = _empty_sheet(tmp_path)

    assert df_from_calamine_xlsx(path, SHEET).shape == (0, 0)
    assert df_from_openpyxl(path, SHEET, min_row=1, has_headers=True).shape == (0, 0)


def test_df_from_openpyxl_without_headers_keeps_the_first_row_as_data(tmp_path):
    """has_headers=False leaves every row in the frame under polars' own column names."""
    path = _plain_table(tmp_path)

    df = df_from_openpyxl(path, SHEET, min_row=1, max_row=None, min_col=1, max_col=None, has_headers=False)

    assert df.height == 4
    assert df.row(0) == ("a", "b")


def test_headerless_row_offset_read_drops_only_the_skipped_rows(tmp_path):
    """The xlsx2csv branch skips start_row rows and invents no header of its own."""
    path = _plain_table(tmp_path)
    settings = ExcelSettings(sheet_name=SHEET, start_row=1, has_headers=False)
    assert select_excel_engine(settings) == "xlsx2csv"

    df = read_excel_table(path, settings)

    assert df.height == 3
    assert df.row(0) == (2, 20)


@pytest.mark.parametrize(
    ("settings", "engine"),
    [
        pytest.param(ExcelSettings(sheet_name=SHEET), "calamine", id="calamine"),
        pytest.param(ExcelSettings(sheet_name=SHEET, type_inference=True), "openpyxl", id="openpyxl"),
        pytest.param(
            ExcelSettings(sheet_name=SHEET, start_row=1, has_headers=False), "xlsx2csv", id="xlsx2csv"
        ),
    ],
)
def test_read_excel_table_logs_the_engine_it_used(tmp_path, caplog, settings, engine):
    """The engine choice is logged at INFO so it lands in the flow log the user reads."""
    path = _plain_table(tmp_path)

    with caplog.at_level(logging.INFO, logger="shared.excel_reader"):
        read_excel_table(path, settings)

    lines = [record.message for record in caplog.records if record.name == "shared.excel_reader"]
    assert any(engine in line and "Reading excel file" in line for line in lines)


def test_a_custom_logger_object_receives_the_engine_line(tmp_path):
    """A NodeLogger-shaped object is used instead of the module logger when one is passed."""
    path = _plain_table(tmp_path)
    recorder = Recorder()

    read_excel_table(path, ExcelSettings(sheet_name=SHEET), logger=recorder)

    assert any("calamine" in line for line in recorder.info_lines)
    assert recorder.warning_lines == []


def test_failing_engine_degrades_to_openpyxl(tmp_path, monkeypatch):
    """A broken calamine read is retried with openpyxl, which does not go through pl.read_excel."""
    path = _plain_table(tmp_path)

    def boom(*args, **kwargs):
        raise RuntimeError("calamine exploded")

    monkeypatch.setattr(excel_reader.pl, "read_excel", boom)
    recorder = Recorder()

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET), logger=recorder)

    assert df.columns == ["a", "b"]
    assert df.height == 3
    warning = "\n".join(recorder.warning_lines)
    assert "calamine" in warning
    assert "Type inference" in warning


def test_failure_on_the_fallback_engine_propagates(tmp_path, monkeypatch):
    """When openpyxl is already the chosen engine there is nothing to degrade to, so it raises."""
    path = _plain_table(tmp_path)

    def boom(*args, **kwargs):
        raise RuntimeError("openpyxl exploded")

    monkeypatch.setattr(excel_reader, "df_from_openpyxl", boom)
    recorder = Recorder()

    with pytest.raises(RuntimeError, match="openpyxl exploded"):
        read_excel_table(path, ExcelSettings(sheet_name=SHEET, type_inference=True), logger=recorder)

    assert recorder.warning_lines == []


def test_end_column_trims_the_frame(tmp_path):
    """The dispatcher applies the node's end bounds on top of whatever the engine returned."""
    path = _blank_interior_header_cell(tmp_path)

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET, end_column=2))

    assert df.columns == ["a", "b"]


def test_ensure_unique_versions_duplicates():
    # The suffix is the occurrence count, so the second "a" is "a_v2" rather than "a_v1".
    assert ensure_unique(["a", "a", "b", "a"]) == ["a", "a_v2", "b", "a_v3"]
    assert ensure_unique(["a", "a_v2", "a"]) == ["a", "a_v2", "a_v3"]
    assert ensure_unique([]) == []


def test_duplicate_headers_are_made_unique(tmp_path):
    """Two columns sharing a name still produce a constructible frame."""

    def fill(ws):
        ws.cell(row=1, column=1, value="a")
        ws.cell(row=1, column=2, value="a")
        for row in range(2, 4):
            ws.cell(row=row, column=1, value=row)
            ws.cell(row=row, column=2, value=row * 10)

    path = _save(tmp_path, "dupes.xlsx", fill)

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET))

    assert df.columns == ["a", "a_v2"]
    assert isinstance(df, pl.DataFrame)


def test_ensure_unique_terminates_when_the_versioned_name_already_exists():
    """['a', 'a_v2', 'a'] looped forever: the retry bumped the candidate's counter, not the item's."""
    assert ensure_unique(["a", "a_v2", "a"]) == ["a", "a_v2", "a_v3"]
    assert ensure_unique(["a", "a_v2", "a_v3", "a", "a"]) == ["a", "a_v2", "a_v3", "a_v4", "a_v5"]


def test_reading_a_sheet_whose_headers_collide_with_a_version_suffix(tmp_path):
    """A header row of a, a_v2, a used to hang the reader with no error and no timeout."""
    def fill(ws):
        for column, header in enumerate(["a", "a_v2", "a"], start=1):
            ws.cell(row=1, column=column, value=header)
        for column in range(1, 4):
            ws.cell(row=2, column=column, value=column)

    path = _save(tmp_path, "version_collision.xlsx", fill)

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET))

    assert df.columns == ["a", "a_v2", "a_v3"]


def _offset_table(tmp_path):
    """The reported layout: three preamble rows, the header on Excel row 4, twenty data rows below it."""

    def fill(ws):
        for _ in range(3):
            ws.append(["preamble", None, None, None])
        ws.append(["id", "name", "qty", "region"])
        for i in range(1, 21):
            ws.append([i, f"item-{i}", i * 3, "north"])

    return _save(tmp_path, "offset.xlsx", fill)


def _headerless_table(tmp_path):
    """Five rows of data anchored at A1 with no header row at all."""

    def fill(ws):
        for i in range(1, 6):
            ws.append([i, f"v{i}"])

    return _save(tmp_path, "headerless.xlsx", fill)


def _normalized(df):
    """Shape plus stringified cells: dtypes and headerless column names vary by engine, the selection must not."""
    return df.shape, [tuple(str(value) for value in row) for row in df.rows()]


RANGE_CASES = [
    pytest.param(ExcelSettings(sheet_name=SHEET, start_row=3, end_row=8), id="rows-3-8"),
    pytest.param(ExcelSettings(sheet_name=SHEET, start_row=3, end_row=8, has_headers=False), id="rows-3-8-headerless"),
    pytest.param(
        ExcelSettings(sheet_name=SHEET, start_row=3, end_row=8, start_column=1, end_column=3), id="rows-3-8-cols-1-3"
    ),
    pytest.param(
        ExcelSettings(sheet_name=SHEET, start_row=3, end_row=8, start_column=1, end_column=3, has_headers=False),
        id="rows-3-8-cols-1-3-headerless",
    ),
    pytest.param(ExcelSettings(sheet_name=SHEET, start_row=3, end_row=4), id="single-data-row"),
    pytest.param(ExcelSettings(sheet_name=SHEET, start_row=3, start_column=1), id="column-offset-without-end"),
    pytest.param(ExcelSettings(sheet_name=SHEET, start_row=3, end_row=99), id="end-row-past-the-sheet"),
]


@pytest.mark.parametrize("engine", ["calamine", "xlsx2csv"])
@pytest.mark.parametrize("settings", RANGE_CASES)
def test_engines_agree_on_row_and_column_selection(tmp_path, engine, settings):
    """Every engine selects the same cells as openpyxl, whose absolute 1-based bounds are unambiguous.

    Toggling 'Type inference' swaps the engine, so any disagreement here means the same range settings
    read a different number of rows depending on a checkbox.
    """
    if engine == "calamine" and not settings.has_headers:
        pytest.skip("df_from_calamine_xlsx always reads the first row of the range as the header")
    path = _offset_table(tmp_path)
    log = logging.getLogger("shared.excel_reader")

    reference = excel_reader._read_with_engine("openpyxl", path, settings, log)
    df = excel_reader._read_with_engine(engine, path, settings, log)

    assert _normalized(df) == _normalized(reference)
    if settings.has_headers:
        assert df.columns == reference.columns


def test_end_row_is_a_zero_based_inclusive_sheet_row(tmp_path):
    """Per the docs, end_row is the zero-based row at which reading stops: end_row=8 keeps Excel row 9."""
    path = _offset_table(tmp_path)

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET, start_row=3, end_row=8))

    assert df.columns == ["id", "name", "qty", "region"]
    assert df.height == 5
    assert df.row(-1) == (5, "item-5", 15, "north")


def test_type_inference_does_not_change_the_row_count(tmp_path):
    """The reported bug: the same headerless range read 8 rows via xlsx2csv but 6 via openpyxl."""
    path = _offset_table(tmp_path)
    base = ExcelSettings(sheet_name=SHEET, start_row=3, end_row=8, has_headers=False)

    without_inference = read_excel_table(path, base)
    with_inference = read_excel_table(path, replace(base, type_inference=True))

    assert select_excel_engine(base) != select_excel_engine(replace(base, type_inference=True))
    assert without_inference.height == with_inference.height == 6
    assert _normalized(without_inference) == _normalized(with_inference)
    assert tuple(str(value) for value in without_inference.row(-1)) == ("5", "item-5", "15", "north")


@pytest.mark.parametrize("sheet_name", [SHEET, None], ids=["named-sheet", "first-sheet"])
def test_headerless_a1_table_keeps_its_first_row(tmp_path, sheet_name):
    """Calamine always treated row 1 as the header, so a headerless sheet lost its first row to the names."""
    path = _headerless_table(tmp_path)
    settings = ExcelSettings(sheet_name=sheet_name, has_headers=False)
    assert select_excel_engine(settings) == "xlsx2csv"

    df = read_excel_table(path, settings)

    assert df.height == 5
    assert df.row(0) == (1, "v1")
    assert "1" not in df.columns


def test_empty_headerless_sheet_reads_as_an_empty_frame(tmp_path):
    """An empty sheet is an empty frame on the headerless path too, with no fallback warning."""
    path = _empty_sheet(tmp_path)
    recorder = Recorder()

    df = read_excel_table(path, ExcelSettings(sheet_name=SHEET, has_headers=False), logger=recorder)

    assert df.shape == (0, 0)
    assert recorder.warning_lines == []
